/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddComponent: typeof import('./src/components/page-designer/components/add-component/add-component.vue')['default']
    DesignComponent: typeof import('./src/components/page-designer/components/design-component/design-component.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    MenuItem: typeof import('./src/components/page-designer/vd-components/vd-menu/menu-item.vue')['default']
    PageDesigner: typeof import('./src/components/page-designer/page-designer.vue')['default']
    ShortcutKeyTip: typeof import('./src/components/page-designer/components/shortcut-key-tip/shortcut-key-tip.vue')['default']
    VdAside: typeof import('./src/components/page-designer/vd-components/vd-aside/vd-aside.vue')['default']
    VdContainer: typeof import('./src/components/page-designer/vd-components/vd-container/vd-container.vue')['default']
    VdFooter: typeof import('./src/components/page-designer/vd-components/vd-footer/vd-footer.vue')['default']
    VdForm: typeof import('./src/components/page-designer/vd-components/vd-form/vd-form.vue')['default']
    VdFormDesigner: typeof import('./src/components/page-designer/components/vd-form-designer/vd-form-designer.vue')['default']
    VdHeader: typeof import('./src/components/page-designer/vd-components/vd-header/vd-header.vue')['default']
    VdLayout: typeof import('./src/components/page-designer/vd-components/vd-layout/vd-layout.vue')['default']
    VdMain: typeof import('./src/components/page-designer/vd-components/vd-main/vd-main.vue')['default']
    VdMenu: typeof import('./src/components/page-designer/vd-components/vd-menu/vd-menu.vue')['default']
    VdMenuItem: typeof import('./src/components/page-designer/components/vd-menu/vd-menu-item.vue')['default']
    VdRouterView: typeof import('./src/components/page-designer/vd-components/vd-router-view/vd-router-view.vue')['default']
    VdSkeleton: typeof import('./src/components/page-designer/components/vd-skeleton/vd-skeleton.vue')['default']
    VdSkeleton1: typeof import('./src/components/page-designer/components/vd-skeleton/vd-skeleton1.vue')['default']
    VdView: typeof import('./src/components/page-designer/vd-components/vd-view/vd-view.vue')['default']
  }
}
