/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddComponent: typeof import('./src/components/add-component/add-component.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    PageDesigner: typeof import('./src/components/page-designer/page-designer.vue')['default']
    VdAside: typeof import('./src/components/page-designer/components/vd-aside/vd-aside.vue')['default']
    VdContainer: typeof import('./src/components/page-designer/components/vd-container/vd-container.vue')['default']
    VdFooter: typeof import('./src/components/page-designer/components/vd-footer/vd-footer.vue')['default']
    VdFormDesigner: typeof import('./src/components/page-designer/components/vd-form-designer/vd-form-designer.vue')['default']
    VdHeader: typeof import('./src/components/page-designer/components/vd-header/vd-header.vue')['default']
    VdLayout: typeof import('./src/components/page-designer/components/vd-layout/vd-layout.vue')['default']
    VdMain: typeof import('./src/components/page-designer/components/vd-main/vd-main.vue')['default']
    VdMenu: typeof import('./src/components/page-designer/components/vd-menu/vd-menu.vue')['default']
    VdRouterView: typeof import('./src/components/page-designer/components/vd-router-view/vd-router-view.vue')['default']
    VdView: typeof import('./src/components/page-designer/components/vd-view/vd-view.vue')['default']
  }
}
