/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddComponent: typeof import('./../src/components/visual-development/components/add-component/add-component.vue')['default']
    ApiConfig: typeof import('./../src/components/visual-development/components/design-component/components/api-config/ApiConfig.vue')['default']
    ApiDomain: typeof import('./../src/components/visual-development/components/design-component/components/d-project/components/ApiDomain.vue')['default']
    CommonField: typeof import('./../src/components/visual-development/components/design-component/components/d-project/components/CommonField.vue')['default']
    DesignComponent: typeof import('./../src/components/visual-development/components/design-component/design-component.vue')['default']
    DesignSkeleton: typeof import('./../src/components/visual-development/components/design-skeleton/design-skeleton.vue')['default']
    DForm: typeof import('./../src/components/visual-development/components/design-component/components/d-form/d-form.vue')['default']
    DProject: typeof import('./../src/components/visual-development/components/design-component/components/d-project/d-project.vue')['default']
    DSearch: typeof import('./../src/components/visual-development/components/design-component/components/d-search/d-search.vue')['default']
    DTable: typeof import('./../src/components/visual-development/components/design-component/components/d-table/d-table.vue')['default']
    DView: typeof import('./../src/components/visual-development/components/design-component/components/d-view/d-view.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExportImportData: typeof import('./../src/components/visual-development/components/export-import-data/ExportImportData.vue')['default']
    FormConfig: typeof import('./../src/components/visual-development/components/design-component/components/form-config/FormConfig.vue')['default']
    GlobalApiConfig: typeof import('./../src/components/visual-development/components/design-component/components/d-project/components/GlobalApiConfig.vue')['default']
    MyColorPicker: typeof import('./../src/components/my-color-picker/my-color-picker.vue')['default']
    MyDividerTitle: typeof import('./../src/components/my-divider-title/my-divider-title.vue')['default']
    MyLabel: typeof import('./../src/components/my-label/my-label.vue')['default']
    OperationsConfig: typeof import('./../src/components/visual-development/components/design-component/components/operations-config/OperationsConfig.vue')['default']
    OptionsConfig: typeof import('./../src/components/visual-development/components/design-component/components/options-config/OptionsConfig.vue')['default']
    ResponsiveCol: typeof import('./../src/components/visual-development/components/design-component/components/responsive-col/responsive-col.vue')['default']
    SaveAsPreset: typeof import('./../src/components/visual-development/components/design-component/components/save-as-preset/save-as-preset.vue')['default']
    SearchConditionConfig: typeof import('./../src/components/visual-development/components/design-component/components/search-condition-config/SearchConditionConfig.vue')['default']
    ShortcutKeyDescription: typeof import('./../src/components/visual-development/components/shortcut-key-description/shortcut-key-description.vue')['default']
    ShortcutKeyOperation: typeof import('./../src/components/visual-development/components/shortcut-key-operation/shortcut-key-operation.vue')['default']
    StaticDataConfig: typeof import('./../src/components/visual-development/components/design-component/components/static-data-config/StaticDataConfig.vue')['default']
    TableColumnConfig: typeof import('./../src/components/visual-development/components/design-component/components/table-column-config/TableColumnConfig.vue')['default']
    VdProject: typeof import('./../src/components/visual-development/components/vd-components/vd-project/vd-project.vue')['default']
    VdSearch: typeof import('./../src/components/visual-development/components/vd-components/vd-search/vd-search.vue')['default']
    VdTable: typeof import('./../src/components/visual-development/components/vd-components/vd-table/vd-table.vue')['default']
    VdView: typeof import('./../src/components/visual-development/components/vd-components/vd-view/vd-view.vue')['default']
    VisualDevelopment: typeof import('./../src/components/visual-development/visual-development.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
